In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv(r'NSL_Regular_Season_Data.csv')
data = data[data["n"] == data["n"]].iloc[:,:17]

team = pd.DataFrame(index=data.sort_values(by="HomeTeam",ascending=True).HomeTeam.unique(),columns=['rating'])

#set base rating
team['rating'] = 1500

data

,n,game_id,HomeTeam,AwayTeam,HomeScore,AwayScore,Home_xG,Away_xG,Home_shots,Away_shots,Home_corner,Away_corner,Home_PK_Goal,Away_PK_Goal,Home_PK_shots,Away_PK_shots,Home_ToP
0,1.0,game_2023_1,PRO,MAN,1.0,1.0,1.63,0.34,17.0,8.0,5.0,4.0,0.0,0.0,0.0,0.0,0.53
1,2.0,game_2023_2,FOR,LEX,1.0,0.0,0.98,0.90,9.0,11.0,5.0,2.0,0.0,0.0,0.0,0.0,0.57
2,3.0,game_2023_3,SJU,DES,1.0,2.0,1.23,1.11,16.0,9.0,6.0,7.0,0.0,0.0,0.0,0.0,0.47
3,4.0,game_2023_4,FAR,ANC,0.0,1.0,2.27,1.08,4.0,14.0,8.0,3.0,0.0,0.0,0.0,0.0,0.51
4,5.0,game_2023_5,DOV,BAK,0.0,0.0,1.90,0.56,17.0,6.0,5.0,3.0,0.0,0.0,0.0,0.0,0.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,472.0,game_2023_472,SAS,TAC,1.0,2.0,0.71,0.51,19.0,12.0,7.0,7.0,0.0,0.0,0.0,0.0,0.42
472,473.0,game_2023_473,DOV,MOB,1.0,1.0,1.70,0.14,19.0,10.0,1.0,5.0,0.0,0.0,0.0,0.0,0.51
473,474.0,game_2023_474,BAK,EUG,3.0,2.0,2.68,1.43,17.0,18.0,9.0,6.0,1.0,0.0,2.0,1.0,0.49
474,475.0,game_2023_475,LRO,LEX,1.0,2.0,2.10,1.30,17.0,6.0,5.0,5.0,0.0,0.0,0.0,0.0,0.51
475,476.0,game_2023_476,WIC,SPR,1.0,1.0,1.73,0.57,13.0,1.0,1.0,7.0,0.0,0.0,0.0,0.0,0.56

In [10]:
k = 100
team['rating'] = 1500
ratings = pd.DataFrame()
ratings.insert(len(ratings),'initial',team)


#do multiple iterations, entering the new ratings as initial ratings
for random_iterations in range(10):
    randomized_data = data.sample(len(data))
    randomized_data = randomized_data.reset_index().iloc[:,1:]
    for iterations in range(5):
    #be able to test different k values
    #for k in range(k,k+1,5):
        for i in range(len(randomized_data)):
            home_team = randomized_data.loc[i,'HomeTeam']
            away_team = randomized_data.loc[i,'AwayTeam']
            home_rating = team.loc[home_team,'rating']
            away_rating = team.loc[away_team,'rating']
            if randomized_data.loc[i,'HomeScore']>randomized_data.loc[i,'AwayScore']:
                home_score = 1
                away_score = 0
            elif randomized_data.loc[i,'HomeScore']<randomized_data.loc[i,'AwayScore']:
                home_score = 0
                away_score = 1
            else:
                home_score = 0.5
                away_score = 0.5
            home_expected = 1/(1+10**((away_rating-home_rating)/400))
            away_expected = 1 - home_expected
            team.loc[randomized_data.loc[i,'HomeTeam'],'rating'] = home_rating + k*(home_score-home_expected)
            team.loc[randomized_data.loc[i,'AwayTeam'],'rating'] = away_rating + k*(away_score-away_expected)
        #ratings.insert(len(ratings.transpose()),'k='+str(k),team)
            
    ratings.insert(len(ratings.transpose()),'randomized_sample_'+str(random_iterations),team)

ratings

,initial,randomized_sample_0,randomized_sample_1,randomized_sample_2,randomized_sample_3,randomized_sample_4,randomized_sample_5,randomized_sample_6,randomized_sample_7,randomized_sample_8,randomized_sample_9
ALB,1500,1530.263204,1449.635781,1471.673934,1372.642649,1357.290453,1446.742801,1415.932700,1407.520734,1462.680352,1364.831520
ANC,1500,1474.009010,1549.508576,1665.508096,1792.795181,1628.632471,1651.282490,1718.635093,1849.685906,1618.529721,1512.994396
AUG,1500,1777.650318,1579.904608,1758.402279,1598.459386,1603.733115,1695.540131,1611.867431,1675.986205,1585.663316,1603.309588
BAK,1500,1322.831735,1449.957577,1547.479142,1392.717748,1336.265065,1425.689865,1475.740784,1337.981285,1438.262712,1495.068241
BOI,1500,1415.050135,1456.541344,1538.513753,1540.629921,1496.643094,1416.190879,1527.205561,1547.530182,1454.559397,1600.729384
CHM,1500,1513.260974,1554.307211,1492.083588,1463.556159,1501.167131,1449.065633,1460.398462,1536.496610,1504.502612,1476.030639
DES,1500,1512.447697,1464.797757,1563.737671,1640.187518,1470.312078,1455.656319,1438.826661,1621.391477,1494.491101,1433.447962
DOV,1500,1590.563118,1634.023846,1409.725358,1701.623671,1574.100831,1529.607759,1593.495781,1579.335483,1589.196893,1666.215931
EUG,1500,1414.602901,1538.509918,1447.276478,1545.432643,1485.955366,1513.900810,1559.001787,1359.521174,1481.540070,1627.558897
FAR,1500,1632.662565,1600.437735,1487.915125,1633.051513,1564.383337,1638.447971,1545.279887,1550.152736,1672.131575,1570.116827
FOR,1500,1459.883695,1394.014856,1444.138527,1461.097283,1491.227747,1438.744503,1354.404649,1512.551943,1525.020148,1427.408166
JAC,1500,1523.450805,1642.507229,1667.416369,1537.804725,1586.041017,1560.008405,1497.772338,1471.491840,1667.448814,1530.587471
LAR,1500,1575.106590,1695.022232,1537.255514,1710.920577,1698.266926,1559.328238,1549.141547,1653.541889,1681.952877,1605.105318
LEX,1500,1579.315610,1541.068581,1497.037010,1450.208072,1592.912396,1582.797364,1386.740902,1594.880077,1516.902096,1414.683254
LRO,1500,1596.281783,1474.596753,1656.137599,1592.265623,1455.799659,1540.014727,1641.523525,1456.966036,1516.121689,1595.206142
MAN,1500,1459.732487,1409.782622,1350.984656,1342.840485,1412.906663,1434.507091,1434.960069,1503.874249,1349.753007,1308.774432
MOB,1500,1487.614541,1429.253479,1427.543247,1449.221638,1486.558710,1425.594680,1516.176250,1440.443592,1404.360485,1406.083678
OAK,1500,1419.858173,1491.839993,1518.512837,1548.104947,1594.714242,1511.263892,1545.825750,1667.468636,1503.339571,1467.780784
PRO,1500,1445.459076,1543.132347,1560.965773,1432.352997,1570.522547,1623.919716,1562.887282,1559.987928,1457.837483,1575.111866
REN,1500,1457.567086,1544.558623,1477.987657,1519.779115,1401.740188,1440.848163,1540.459004,1456.492256,1508.224044,1477.214348
SAS,1500,1542.395463,1458.003515,1490.172103,1493.658636,1392.678298,1560.748151,1494.130421,1470.580924,1557.455585,1552.901306
SFS,1500,1613.992091,1542.362666,1452.697738,1565.370140,1506.613302,1524.293369,1584.050152,1457.743150,1567.768438,1648.671990
SJU,1500,1397.202077,1334.999734,1351.829608,1310.639806,1412.822891,1339.856537,1403.410526,1334.864693,1382.464683,1490.098315
SPR,1500,1519.019499,1519.900175,1703.018765,1462.087841,1672.459837,1626.377358,1505.826776,1487.737840,1565.274725,1557.361189
TAC,1500,1350.092893,1246.323994,1261.134641,1295.736320,1346.087922,1281.899097,1185.340359,1330.067205,1277.659270,1259.173398
TOL,1500,1614.825096,1622.304098,1528.064954,1459.313048,1490.377177,1519.205817,1602.941468,1433.288028,1485.845398,1552.677311
TUC,1500,1421.227691,1275.202956,1405.825466,1373.389828,1486.209389,1326.627465,1340.859193,1181.735178,1353.722165,1331.615363
WIC,1500,1353.633690,1557.501791,1286.962112,1314.112532,1383.578149,1481.840771,1507.165641,1520.682742,1377.291773,1449.242285

In [27]:
scores = pd.DataFrame()
final_home_score = ratings.sort_values('iteration_home=9',ascending=False)['iteration_home=9'].reset_index().rename(columns={"index": "home_team"})
final_away_score = ratings.sort_values('iteration_away=9',ascending=False)['iteration_away=9'].reset_index().rename(columns={"index": "away_team"})
scores = pd.concat([final_home_score,final_away_score],axis=1)
scores

   home_team  iteration_home=9 away_team  iteration_away=9
0        AUG       1747.596639       AUG       1735.900056
1        SPR       1624.189260       PRO       1722.369076
2        ANC       1612.766233       LAR       1720.207171
3        LAR       1573.985799       DES       1708.741832
4        LEX       1565.242682       FAR       1636.877506
5        DOV       1560.898345       JAC       1636.485791
6        JAC       1558.400330       MOB       1604.785320
7        FAR       1546.379492       OAK       1596.169081
8        TOL       1532.674403       CHM       1584.924751
9        SAS       1527.426405       LRO       1561.484822
10       LRO       1512.212337       LEX       1546.047521
11       BAK       1509.829588       ALB       1540.396691
12       OAK       1501.740719       ANC       1533.843258
13       SFS       1498.439997       SFS       1530.087017
14       FOR       1486.273149       SAS       1505.114016
15       EUG       1472.058123       TOL       1462.058151
16       REN       1468.246146       DOV       1448.545681
17       SJU       1467.899701       REN       1438.397446
18       PRO       1445.671254       SPR       1430.312701
19       MAN       1444.204628       BOI       1421.459786
20       ALB       1426.126851       WIC       1412.360881
21       MOB       1405.053511       MAN       1411.521399
22       DES       1399.120908       TAC       1404.899163
23       CHM       1395.969030       BAK       1404.486387
24       BOI       1369.246093       EUG       1386.021406
25       WIC       1367.333959       FOR       1371.194832
26       TUC       1363.232404       TUC       1299.918885
27       TAC       1305.531576       SJU       1257.639808

In [28]:
scores.to_csv('elo_ranked_home_and_away.csv')